interactions:
- request:
    body: '{"recordStartNumber": 0, "recordTotalQuantity": 1, "sortDataBag": [], "searchText":
      "applicationNumberText:(\"09089931\")"}'
    headers:
      accept:
      - '*/*'
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      content-length:
      - '123'
      content-type:
      - application/json
      host:
      - developer.uspto.gov
      user-agent:
      - python-httpx/0.27.0
    method: POST
    uri: https://developer.uspto.gov/ptab-api/proceedings/json
  response:
    content: "{\"aggregationData\":{\"proceedingTypeCategory\":[{\"name\":\"AIA Trial\",\"quantity\":1,\"nestedFacetTypeName\":\"subproceedingTypeCategory\",\"nestedFacetBag\":[{\"name\":\"IPR\",\"quantity\":1}]}],\"respondentTechnologyCenterNumber\":[{\"name\":\"2800\",\"quantity\":1,\"nestedFacetBag\":[]}],\"proceedingStatusCategory\":[{\"name\":\"Terminated-Settled\",\"quantity\":1}]},\"results\":[{\"institutionDecisionDate\":\"09-28-2016\",\"proceedingFilingDate\":\"04-01-2016\",\"accordedFilingDate\":\"04-01-2016\",\"proceedingStatusCategory\":\"Terminated-Settled\",\"proceedingNumber\":\"IPR2016-00833\",\"proceedingLastModifiedDate\":\"07-06-2017\",\"proceedingTypeCategory\":\"AIA
      Trial\",\"subproceedingTypeCategory\":\"IPR\",\"respondentTechnologyCenterNumber\":\"2800\",\"respondentPatentOwnerName\":\"Silicon
      Genesis Corporation\",\"respondentPartyName\":\"Silicon Genesis Corporation\",\"respondentInventorName\":\"FRANCOIS
      HENLEY\",\"respondentCounselName\":\"Margaux Nair\",\"respondentGrantDate\":\"08-15-2000\",\"respondentPatentNumber\":\"6103599\",\"respondentApplicationNumberText\":\"09089931\",\"petitionerPartyName\":\"Commissariat
      a l\u2019Energie Atomique et aux Energies Alternatives\",\"petitionerCounselName\":\"Paul
      McGowan\",\"decisionDate\":\"07-06-2017\",\"additionalRespondentPartyDataBag\":[]}],\"recordTotalQuantity\":1}"
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - accept, authorization, content-type, x-requested-with
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS, PUT
      Access-Control-Allow-Origin:
      - '*'
      Access-Control-Max-Age:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Date:
      - Mon, 05 Aug 2024 22:16:00 GMT
      Strict-Transport-Security:
      - max-age=31536000;
      Transfer-Encoding:
      - chunked
      Vary:
      - Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
    http_version: HTTP/1.1
    status_code: 200
- request:
    body: '{"recordStartNumber": 0, "recordTotalQuantity": 1, "sortDataBag": [], "searchText":
      "applicationNumberText:(\"09089931\")"}'
    headers:
      accept:
      - '*/*'
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      content-length:
      - '123'
      content-type:
      - application/json
      host:
      - developer.uspto.gov
      user-agent:
      - python-httpx/0.27.0
    method: POST
    uri: https://developer.uspto.gov/ptab-api/proceedings/json
  response:
    content: "{\"aggregationData\":{\"proceedingTypeCategory\":[{\"name\":\"AIA Trial\",\"quantity\":1,\"nestedFacetTypeName\":\"subproceedingTypeCategory\",\"nestedFacetBag\":[{\"name\":\"IPR\",\"quantity\":1}]}],\"respondentTechnologyCenterNumber\":[{\"name\":\"2800\",\"quantity\":1,\"nestedFacetBag\":[]}],\"proceedingStatusCategory\":[{\"name\":\"Terminated-Settled\",\"quantity\":1}]},\"results\":[{\"institutionDecisionDate\":\"09-28-2016\",\"proceedingFilingDate\":\"04-01-2016\",\"accordedFilingDate\":\"04-01-2016\",\"proceedingStatusCategory\":\"Terminated-Settled\",\"proceedingNumber\":\"IPR2016-00833\",\"proceedingLastModifiedDate\":\"07-06-2017\",\"proceedingTypeCategory\":\"AIA
      Trial\",\"subproceedingTypeCategory\":\"IPR\",\"respondentTechnologyCenterNumber\":\"2800\",\"respondentPatentOwnerName\":\"Silicon
      Genesis Corporation\",\"respondentPartyName\":\"Silicon Genesis Corporation\",\"respondentInventorName\":\"FRANCOIS
      HENLEY\",\"respondentCounselName\":\"Margaux Nair\",\"respondentGrantDate\":\"08-15-2000\",\"respondentPatentNumber\":\"6103599\",\"respondentApplicationNumberText\":\"09089931\",\"petitionerPartyName\":\"Commissariat
      a l\u2019Energie Atomique et aux Energies Alternatives\",\"petitionerCounselName\":\"Paul
      McGowan\",\"decisionDate\":\"07-06-2017\",\"additionalRespondentPartyDataBag\":[]}],\"recordTotalQuantity\":1}"
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Headers:
      - accept, authorization, content-type, x-requested-with
      Access-Control-Allow-Methods:
      - GET, POST, OPTIONS, PUT
      Access-Control-Allow-Origin:
      - '*'
      Access-Control-Max-Age:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Date:
      - Mon, 05 Aug 2024 22:16:01 GMT
      Strict-Transport-Security:
      - max-age=31536000;
      Transfer-Encoding:
      - chunked
      Vary:
      - Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
    http_version: HTTP/1.1
    status_code: 200
version: 1
