# ********************************************************************************
# *  WARNING: This code is automatically generated by unasync.py. Do not edit!   *
# ********************************************************************************
from .family import FamilyAsyncApi

NS = {
    "http://ops.epo.org": None,
    "http://www.epo.org/exchange": None,
    "http://www.epo.org/fulltext": None,
    "http://www.epo.org/register": None,
}


def test_api():
    result = FamilyAsyncApi.get_family("EP1000000A1")
    count = int(result.find(".//{http://ops.epo.org}patent-family").attrib["total-result-count"])
    assert count >= 6
