# ********************************************************************************
# *  WARNING: This code is automatically generated by unasync.py. Do not edit!   *
# ********************************************************************************
import lxml.etree as ET

from ..http_client import PatentClientHttpClient
from .auth import ops_auth
from patent_client import function_cache


class FamilyAsyncApi:
    http_client = PatentClientHttpClient(auth=ops_auth)

    @classmethod
    @function_cache
    def get_family(cls, number, doc_type="publication", format="docdb"):
        url = f"http://ops.epo.org/3.2/rest-services/family/{doc_type}/{format}/{number}"
        response = cls.http_client.get(url)
        return ET.fromstring(response.content)
