# ********************************************************************************
# *  WARNING: This code is automatically generated by unasync.py. Do not edit!   *
# ********************************************************************************
from .legal import LegalAsyncApi


def test_get_legal():
    result = LegalAsyncApi.get_legal("EP1000000A1")
    assert len(result.findall(".//{http://ops.epo.org}legal")) >= 50


def test_get_legal_code_spreadsheet():
    result = LegalAsyncApi.get_legal_code_spreadsheet()
    assert len(result.xpath(".//tr/td[contains(text(), 'Legal event codes')]/../td[4]")) > 0
