repos:
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
      args: ['--line-length=120',]
      language_version: python3
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
        args: ['--config=.flake8']
-   repo: meta
    hooks:
    -   id: check-hooks-apply
