repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.9
      args: ['--line-length=120',]
-   repo: https://github.com/hadialqattan/pycln
    rev: v1.3.3 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
    - id: pycln
      args: [--config=pyproject.toml]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3.9
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
        args: ['--config=.flake8']
-   repo: meta
    hooks:
    -   id: check-hooks-apply
