# ********************************************************************************
# *         WARNING: This file is automatically generated by unasync.py.         *
# *                             DO NOT MANUALLY EDIT                             *
# *        Source File: patent_client/_async/uspto/bulk_data/api_test.py         *
# ********************************************************************************

import pytest

from .api import BulkDataApi
from .model import File, Product


def test_can_get_latest():
    latest = BulkDataApi.get_latest()
    first = latest[0]
    assert isinstance(first, Product)
    assert isinstance(first.files[0], File)


def test_can_get_by_short_name():
    first = BulkDataApi.get_by_short_name("PTGRXML")
    assert isinstance(first, Product)
    assert isinstance(first.files[0], File)


def test_can_get_by_short_name_with_date_range():
    first = BulkDataApi.get_by_short_name("PTGRXML", from_date="2023-06-01", to_date="2023-08-01")
    assert isinstance(first, Product)
    assert isinstance(first.files[0], File)
    assert len(first.files) == 10


@pytest.mark.no_vcr
@pytest.mark.skip(reason="This test is too slow")
def test_can_download_file(tmpdir):
    product = BulkDataApi.get_by_short_name("PTGRXML")
    file = product.files[0]
    file.adownload(tmpdir)
    assert len(list(tmpdir.listdir())) == 1
