# ********************************************************************************
# *  WARNING: This code is automatically generated by unasync.py. Do not edit!   *
# ********************************************************************************
import pytest


@pytest.fixture
def anyio_backend():
    return "asyncio"
