SEARCH_PARAMS = {
    "Sect1": "PTO2",
    "Sect2": "HITOFF",
    "u": "/netahtml/PTO/search-adv.htm",
    "r": "0",
    "p": "1",
    "f": "S",
    "l": "50",
    "Query": "",
    "d": "PTXT",
}

SEARCH_FIELDS = {
    "patent_number": "PN",
    "issue_date": "ISD",
    "title": "TTL",
    "abstract": "ABST",
    "claims": "ACLM",
    "specification": "SPEC",
    "current_us_classification": "CCL",
    "current_cpc_classification": "CPC",
    "current_cpc_classification_class": "CPCL",
    "international_classification": "ICL",
    "application_serial_number": "APN",
    "application_date": "APD",
    "application_type": "APT",
    "government_interest": "GOVT",
    "patent_family_id": "FMID",
    "parent_case_information": "PARN",
    "related_us_app._data": "RLAP",
    "related_application_filing_date": "RLFD",
    "foreign_priority": "PRIR",
    "priority_filing_date": "PRAD",
    "pct_information": "PCT",
    "pct_filing_date": "PTAD",
    "pct_national_stage_filing_date": "PT3D",
    "prior_published_document_date": "PPPD",
    "reissue_data": "REIS",
    "reissued_patent_application_filing_date": "RPAF",
    "130_b_affirmation_flag": "AFFF",
    "130_b_affirmation_statement": "AFFT",
    "inventor_name": "IN",
    "inventor_city": "IC",
    "inventor_state": "IS",
    "inventor_country": "ICN",
    "applicant_name": "AANM",
    "applicant_city": "AACI",
    "applicant_state": "AAST",
    "applicant_country": "AACO",
    "applicant_type": "AAAT",
    "attorney_or_agent": "LREP",
    "assignee_name": "AN",
    "assignee_city": "AC",
    "assignee_state": "AS",
    "assignee_country": "ACN",
    "primary_examiner": "EXP",
    "assistant_examiner": "EXA",
    "referenced_by": "REF",
    "foreign_references": "FREF",
    "other_references": "OREF",
    "certificate_of_correction": "COFC",
    "reexamination_certificate": "REEX",
    "ptab_trial_certificate": "PTAB",
    "supplemental_exam_certificate": "SEC",
    "international_registration_number": "ILRN",
    "international_registration_date": "ILRD",
    "international_registration_publication_date": "ILPD",
    "hague_international_filing_date": "ILFD",
}

SEARCH_PARAMS = {
    "Sect1": "PTO2",
    "Sect2": "HITOFF",
    "u": "/netahtml/PTO/search-adv.htm",
    "r": "0",
    "p": "1",
    "f": "S",
    "l": "50",
    "Query": "",
    "d": "PTXT",
}

SEARCH_URL = "https://patft.uspto.gov/netacgi/nph-Parser"

PUBLICATION_URL = (
    "https://patft.uspto.gov/netacgi/nph-Parser?"
    "Sect1=PTO1&Sect2=HITOFF&d=PALL&p=1&"
    "u=%2Fnetahtml%2FPTO%2Fsrchnum.htm&r=1&f=G&l=50&s1={publication_number}.PN.&"
    "OS=PN/{publication_number}&RS=PN/{publication_number}"
)
