# ********************************************************************************
# *         WARNING: This file is automatically generated by unasync.py.         *
# *                             DO NOT MANUALLY EDIT                             *
# *     Source File: patent_client/_async/epo/ops/number_service/__init__.py     *
# ********************************************************************************

from .errors import build_error_dir

error_dir = build_error_dir()
