# ********************************************************************************
# *         WARNING: This file is automatically generated by unasync.py.         *
# *                             DO NOT MANUALLY EDIT                             *
# *         Source File: patent_client/_async/uspto/public_search/api.py         *
# ********************************************************************************

import asyncio
from pathlib import Path

import httpx

from .model import PublicSearchBiblioPage
from .model import PublicSearchDocument

import httpx

session = httpx.Client(
    headers={
        "X-Requested-With": "XMLHttpRequest",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    },
    http2=True,
    follow_redirects=True,
)


class UsptoException(Exception):
    pass


def force_list(obj):
    if not isinstance(obj, list):
        return [
            obj,
        ]
    return obj


class PublicSearchApi:
    def __init__(self):
        self.session = dict()
        self.case_id = None

    def run_query(
        self,
        query,
        start=0,
        limit=500,
        sort="date_publ desc",
        default_operator="OR",
        sources=["US-PGPUB", "USPAT", "USOCR"],
        expand_plurals=True,
        british_equivalents=True,
    ) -> "PublicSearch":
        if self.case_id is None:
            self.get_session()
        url = "https://ppubs.uspto.gov/dirsearch-public/searches/searchWithBeFamily"
        data = {
            "start": start,
            "pageCount": limit,
            "sort": sort,
            "docFamilyFiltering": "familyIdFiltering",
            "searchType": 1,
            "familyIdEnglishOnly": True,
            "familyIdFirstPreferred": "US-PGPUB",
            "familyIdSecondPreferred": "USPAT",
            "familyIdThirdPreferred": "FPRS",
            "showDocPerFamilyPref": "showEnglish",
            "queryId": 0,
            "tagDocSearch": False,
            "query": {
                "caseId": self.case_id,
                "hl_snippets": "2",
                "op": default_operator,
                "q": query,
                "queryName": query,
                "highlights": "1",
                "qt": "brs",
                "spellCheck": False,
                "viewName": "tile",
                "plurals": expand_plurals,
                "britishEquivalents": british_equivalents,
                "databaseFilters": [],
                "searchType": 1,
                "ignorePersist": True,
                "userEnteredQuery": query,
            },
        }
        for s in force_list(sources):
            data["query"]["databaseFilters"].append(
                {"databaseName": s, "countryCodes": []}
            )
        counts = self.make_request(
            "POST",
            "https://ppubs.uspto.gov/dirsearch-public/searches/counts",
            json=data["query"],
        )
        counts.raise_for_status()
        query_response = self.make_request("POST", url, json=data)
        query_response.raise_for_status()
        result = query_response.json()
        if result.get("error", None) is not None:
            raise UsptoException(
                f"Error #{result['error']['errorCode']}\n{result['error']['errorMessage']}"
            )
        return PublicSearchBiblioPage.model_validate(result)

    def make_request(self, method, url, **kwargs):
        response = session.request(method, url, **kwargs)
        if response.status_code == 403:
            self.get_session()
            response = session.request(method, url, **kwargs)
        if response.status_code == 429:
            wait_time = int(response.headers["x-rate-limit-retry-after-seconds"]) + 1
            asyncio.sleep(wait_time)
            response = session.request(method, url, **kwargs)
        return response

    def get_document(self, bib) -> "PublicSearchDocument":
        url = f"https://ppubs.uspto.gov/dirsearch-public/internal/patents/{bib.guid}/highlight"
        params = {
            "queryId": 1,
            "source": bib.type,
            "includeSections": True,
            "uniqueId": None,
        }
        response = session.get(url, params=params)
        response.raise_for_status()
        return PublicSearchDocument.model_validate(response.json())

    def get_session(self):
        session.cookies = httpx.Cookies()
        response = session.get("https://ppubs.uspto.gov/pubwebapp/")
        url = "https://ppubs.uspto.gov/dirsearch-public/users/me/session"
        response = session.post(
            url,
            json=-1,
            headers={
                "X-Access-Token": "null",
                "referer": "https://ppubs.uspto.gov/pubwebapp/",
            },
        )  # json=str(random.randint(10000, 99999)))
        self.session = response.json()
        self.case_id = self.session["userCase"]["caseId"]
        self.access_token = response.headers["X-Access-Token"]
        session.headers["X-Access-Token"] = self.access_token
        return self.session

    def _request_save(self, obj):
        page_keys = [
            f"{obj.image_location}/{i:0>8}.tif"
            for i in range(1, obj.document_structure.page_count + 1)
        ]
        response = session.post(
            "https://ppubs.uspto.gov/dirsearch-public/print/imageviewer",
            json={
                "caseId": self.case_id,
                "pageKeys": page_keys,
                "patentGuid": obj.guid,
                "saveOrPrint": "save",
                "source": obj.type,
            },
        )
        if response.status_code == 500:
            raise UsptoException(response.text)
        return response.text

    def download_image(self, obj, path="."):
        out_path = Path(path).expanduser() / f"{obj.guid}.pdf"
        if out_path.exists():
            return out_path
        if self.case_id is None:
            self.get_session()
        try:
            print_job_id = self._request_save(obj)
        except httpx.HTTPStatusError:
            self.get_session()
            print_job_id = self._request_save(obj)
        while True:
            response = session.post(
                "https://ppubs.uspto.gov/dirsearch-public/print/print-process",
                json=[
                    print_job_id,
                ],
            )
            response.raise_for_status()
            print_data = response.json()
            if print_data[0]["printStatus"] == "COMPLETED":
                break
            asyncio.sleep(1)
        pdf_name = print_data[0]["pdfName"]
        with out_path.open("wb") as f:
            try:
                request = session.build_request(
                    "GET",
                    f"https://ppubs.uspto.gov/dirsearch-public/print/save/{pdf_name}",
                )
                response = session.send(request, stream=True)
                response.raise_for_status()
                for chunk in response.iter_bytes():
                    if chunk:
                        f.write(chunk)
            except httpx.HTTPStatusError as e:
                response.close()
                raise e
        return out_path
