# ********************************************************************************
# *  WARNING: This code is automatically generated by unasync.py. Do not edit!   *
# ********************************************************************************
import pytest

from .assignment import AssignmentApi


def test_lookup():
    tree = AssignmentApi.lookup("Apple", "OwnerName")
    assert len(tree.findall(".//doc")) == 8


def test_download_pdf(tmp_path):
    path = tmp_path / "test.pdf"
    AssignmentApi.download_pdf("44101", "610", path)
    assert path.exists()
    assert path.stat().st_size > 0
