# ********************************************************************************
# *  WARNING: This code is automatically generated by unasync.py. Do not edit!   *
# ********************************************************************************
import pytest

from .bulk_data import BulkDataApi


def test_can_get_latest():
    latest = BulkDataApi.get_latest()
    assert len(latest) > 25


def test_can_get_by_short_name():
    result = BulkDataApi.get_by_short_name("PTGRXML")
    assert result["productShortName"] == "PTGRXML"


def test_can_get_by_short_name_with_date_range():
    result = BulkDataApi.get_by_short_name("PTGRXML", from_date="2023-06-01", to_date="2023-08-01")
    assert result["productShortName"] == "PTGRXML"
    assert len(result["productFiles"]) == 10
    assert result["productFiles"][0]["fileReleaseDate"] == "2023-06-06"
    assert result["productFiles"][-1]["fileReleaseDate"] == "2023-08-01"
