# ********************************************************************************
# *  WARNING: This code is automatically generated by unasync.py. Do not edit!   *
# ********************************************************************************
import pytest

from .global_dossier import GlobalDossierApi


def test_get_dossier():
    result = GlobalDossierApi.get_dossier("16123456")
    assert result["id"] == "16123456"


def test_get_doc_list():
    result = GlobalDossierApi.get_doc_list("US", "15644139", "A")
    assert len(result["docs"]) >= 34


def test_get_document(tmp_path):
    result = GlobalDossierApi.get_document("US", "201715644139.A", "JZBXRMELRXEAPX4", out_path=tmp_path)
    assert result.exists()
