# ********************************************************************************
# *  WARNING: This code is automatically generated by unasync.py. Do not edit!   *
# ********************************************************************************
import pytest

from .peds import PatentExaminationDataSystemApi


def test_can_get_app():
    result = PatentExaminationDataSystemApi.create_query("applId:(16123456)")
    assert result["queryResults"]["searchResponse"]["response"]["numFound"] == 1
    assert result["queryResults"]["searchResponse"]["response"]["docs"][0]["applId"] == "16123456"


def test_can_search_by_customer_number():
    result = PatentExaminationDataSystemApi().create_query("appCustNumber:(70155)")
    assert result["queryResults"]["searchResponse"]["response"]["numFound"] > 10


def test_can_limit_by_rows():
    result = PatentExaminationDataSystemApi().create_query("appCustNumber:(70155)", rows=5)
    assert result["queryResults"]["searchResponse"]["response"]["numFound"] >= 5
