# ********************************************************************************
# *  WARNING: This code is automatically generated by unasync.py. Do not edit!   *
# ********************************************************************************
import pytest

from .ptab import PtabApi


def test_can_get_document():
    page = PtabApi.get_documents(document_identifier="170680401")
    assert len(page["results"]) == 1


def test_can_get_document_range():
    page = PtabApi.get_documents(
        proceeding_number="IPR2022-00037",
        document_filing_date=("2023-01-01", "2023-09-15"),
    )
    assert len(page["results"]) == 25


def test_can_get_proceeding():
    page = PtabApi.get_proceedings(proceeding_number="IPR2022-00037")
    assert len(page["results"]) == 1
