# ********************************************************************************
# *         WARNING: This file is automatically generated by unasync.py.         *
# *                             DO NOT MANUALLY EDIT                             *
# *      Source File: patent_client/_async/uspto/global_dossier/api_test.py      *
# ********************************************************************************

from pathlib import Path

from .api import GlobalDossierApi
from .model import DocumentList, GlobalDossier


def test_get_file():
    api = GlobalDossierApi()
    doc_number = "16740760"
    type_code = "application"
    office_code = "US"
    response = api.get_file(doc_number, type_code, office_code)
    assert isinstance(response, GlobalDossier)
    assert response.country == "US"
    assert response.id == "16740760"


def test_get_doc_list():
    api = GlobalDossierApi()
    country = "US"
    doc_number = "16740760"
    kind_code = "A"
    response = api.get_doc_list(country, doc_number, kind_code)
    assert isinstance(response, DocumentList)
    assert len(response.docs) > 0


def test_get_document(tmp_path: Path):
    api = GlobalDossierApi()
    country = "US"
    doc_number = "201816123456.A"
    document_id = "KJM2MWIEDFLYX10"
    out_path = tmp_path / "test_document.pdf"
    api.get_document(country, doc_number, document_id, out_path)
    assert out_path.exists()
    assert out_path.stat().st_size > 0
