# ********************************************************************************
# *         WARNING: This file is automatically generated by unasync.py.         *
# *                             DO NOT MANUALLY EDIT                             *
# *            Source File: patent_client/_async/uspto/ptab/errors.py            *
# ********************************************************************************


class InvalidFieldError(ValueError):
    """Raised when an invalid field is provided in a search query."""

    pass


class PtabApiError(Exception):
    """Custom exception for PTAB API errors."""

    pass
