# ********************************************************************************
# *         WARNING: This file is automatically generated by unasync.py.         *
# *                             DO NOT MANUALLY EDIT                             *
# *            Source File: patent_client/_async/uspto/ptab/model.py             *
# ********************************************************************************

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from patent_client.util.pydantic_util import BaseModel


class Party(BaseModel):
    application_number_text: Optional[str] = Field(None, alias="applicationNumberText")
    inventor_name: Optional[str] = Field(None, alias="inventorName")
    patent_number: Optional[str] = Field(None, alias="patentNumber")
    party_name: Optional[str] = Field(None, alias="partyName")


class AggregationInfo(BaseModel):
    name: Optional[str] = None
    quantity: Optional[int] = None
    nested_facet_type_name: Optional[str] = Field(None, alias="nestedFacetTypeName")
    nested_facet_bag: Optional[List["AggregationInfo"]] = Field(None, alias="nestedFacetBag")


class SearchOutput(BaseModel):
    aggregation_data: Optional[Dict[str, List[AggregationInfo]]] = Field(
        None, alias="aggregationData"
    )
    results: Optional[Any] = None
    record_total_quantity: Optional[int] = Field(None, alias="recordTotalQuantity")
    response_message: Optional[str] = Field(None, alias="responseMessage")


class PtabProceeding(BaseModel):
    last_modified_date: Optional[datetime] = Field(None, alias="lastModifiedDate")
    last_modified_user_id: Optional[str] = Field(None, alias="lastModifiedUserId")
    institution_decision_date: Optional[str] = Field(None, alias="institutionDecisionDate")
    proceeding_filing_date: Optional[str] = Field(None, alias="proceedingFilingDate")
    accorded_filing_date: Optional[str] = Field(None, alias="accordedFilingDate")
    proceeding_status_category: Optional[str] = Field(None, alias="proceedingStatusCategory")
    proceeding_number: Optional[str] = Field(None, alias="proceedingNumber")
    proceeding_last_modified_date: Optional[str] = Field(None, alias="proceedingLastModifiedDate")
    proceeding_type_category: Optional[str] = Field(None, alias="proceedingTypeCategory")
    subproceeding_type_category: Optional[str] = Field(None, alias="subproceedingTypeCategory")
    respondent_technology_center_number: Optional[str] = Field(
        None, alias="respondentTechnologyCenterNumber"
    )
    respondent_patent_owner_name: Optional[str] = Field(None, alias="respondentPatentOwnerName")
    respondent_party_name: Optional[str] = Field(None, alias="respondentPartyName")
    respondent_group_art_unit_number: Optional[str] = Field(
        None, alias="respondentGroupArtUnitNumber"
    )
    respondent_inventor_name: Optional[str] = Field(None, alias="respondentInventorName")
    respondent_counsel_name: Optional[str] = Field(None, alias="respondentCounselName")
    respondent_grant_date: Optional[str] = Field(None, alias="respondentGrantDate")
    respondent_patent_number: Optional[str] = Field(None, alias="respondentPatentNumber")
    respondent_application_number_text: Optional[str] = Field(
        None, alias="respondentApplicationNumberText"
    )
    petitioner_technology_center_number: Optional[str] = Field(
        None, alias="petitionerTechnologyCenterNumber"
    )
    petitioner_patent_owner_name: Optional[str] = Field(None, alias="petitionerPatentOwnerName")
    petitioner_party_name: Optional[str] = Field(None, alias="petitionerPartyName")
    petitioner_group_art_unit_number: Optional[str] = Field(
        None, alias="petitionerGroupArtUnitNumber"
    )
    petitioner_inventor_name: Optional[str] = Field(None, alias="petitionerInventorName")
    petitioner_counsel_name: Optional[str] = Field(None, alias="petitionerCounselName")
    petitioner_grant_date: Optional[str] = Field(None, alias="petitionerGrantDate")
    petitioner_patent_number: Optional[str] = Field(None, alias="petitionerPatentNumber")
    petitioner_application_number_text: Optional[str] = Field(
        None, alias="petitionerApplicationNumberText"
    )
    decision_date: Optional[str] = Field(None, alias="decisionDate")
    appellant_technology_center_number: Optional[str] = Field(
        None, alias="appellantTechnologyCenterNumber"
    )
    appellant_patent_owner_name: Optional[str] = Field(None, alias="appellantPatentOwnerName")
    appellant_party_name: Optional[str] = Field(None, alias="appellantPartyName")
    third_party_name: Optional[str] = Field(None, alias="thirdPartyName")
    appellant_group_art_unit_number: Optional[str] = Field(
        None, alias="appellantGroupArtUnitNumber"
    )
    appellant_inventor_name: Optional[str] = Field(None, alias="appellantInventorName")
    appellant_counsel_name: Optional[str] = Field(None, alias="appellantCounselName")
    appellant_grant_date: Optional[str] = Field(None, alias="appellantGrantDate")
    appellant_patent_number: Optional[str] = Field(None, alias="appellantPatentNumber")
    appellant_application_number_text: Optional[str] = Field(
        None, alias="appellantApplicationNumberText"
    )
    appellant_publication_date: Optional[str] = Field(None, alias="appellantPublicationDate")
    appellant_publication_number: Optional[str] = Field(None, alias="appellantPublicationNumber")
    documents: Optional[str] = None
    docket_notice_mail_date: Optional[str] = Field(None, alias="docketNoticeMailDate")
    declaration_date: Optional[str] = Field(None, alias="declarationDate")
    second_respondent_party_name: Optional[str] = Field(None, alias="secondRespondentPartyName")
    second_respondent_appl_number_text: Optional[str] = Field(
        None, alias="secondRespondentApplNumberText"
    )
    second_respondent_patent_number: Optional[str] = Field(
        None, alias="secondRespondentPatentNumber"
    )
    second_respondent_grant_date: Optional[str] = Field(None, alias="secondRespondentGrantDate")
    second_respondent_patent_owner_name: Optional[str] = Field(
        None, alias="secondRespondentPatentOwnerName"
    )
    second_respondent_inventor_name: Optional[str] = Field(
        None, alias="secondRespondentInventorName"
    )
    second_respondent_counsel_name: Optional[str] = Field(None, alias="secondRespondentCounselName")
    second_respondent_gau_number: Optional[str] = Field(None, alias="secondRespondentGAUNumber")
    second_respondent_tech_center_number: Optional[str] = Field(
        None, alias="secondRespondentTechCenterNumber"
    )
    second_respondent_pub_number: Optional[str] = Field(None, alias="secondRespondentPubNumber")
    second_respondent_publication_date: Optional[str] = Field(
        None, alias="secondRespondentPublicationDate"
    )
    respondent_publication_number: Optional[str] = Field(None, alias="respondentPublicationNumber")
    respondent_publication_date: Optional[str] = Field(None, alias="respondentPublicationDate")
    style_name_text: Optional[str] = Field(None, alias="styleNameText")
    additional_respondent_party_data_bag: Optional[List[Party]] = Field(
        None, alias="additionalRespondentPartyDataBag"
    )


class PtabDocument(BaseModel):
    last_modified_date: Optional[datetime] = Field(None, alias="lastModifiedDate")
    last_modified_user_id: Optional[str] = Field(None, alias="lastModifiedUserId")
    filing_party_category: Optional[str] = Field(None, alias="filingPartyCategory")
    document_number: Optional[str] = Field(None, alias="documentNumber")
    document_name: Optional[str] = Field(None, alias="documentName")
    document_category: Optional[str] = Field(None, alias="documentCategory")
    document_title_text: Optional[str] = Field(None, alias="documentTitleText")
    proceeding_number: Optional[str] = Field(None, alias="proceedingNumber")
    document_filing_date: Optional[str] = Field(None, alias="documentFilingDate")
    document_type_name: Optional[str] = Field(None, alias="documentTypeName")
    proceeding_type_category: Optional[str] = Field(None, alias="proceedingTypeCategory")
    subproceeding_type_category: Optional[str] = Field(None, alias="subproceedingTypeCategory")
    media_type_category: Optional[str] = Field(None, alias="mediaTypeCategory")
    document_size: Optional[str] = Field(None, alias="documentSize")
    document_identifier: Optional[str] = Field(None, alias="documentIdentifier")
    object_uu_id: Optional[str] = Field(None, alias="objectUuId")


class PtabDecision(BaseModel):
    last_modified_date: Optional[datetime] = Field(None, alias="lastModifiedDate")
    last_modified_user_id: Optional[str] = Field(None, alias="lastModifiedUserId")
    proceeding_number: Optional[str] = Field(None, alias="proceedingNumber")
    decision_type_category: Optional[str] = Field(None, alias="decisionTypeCategory")
    subdecision_type_category: Optional[str] = Field(None, alias="subdecisionTypeCategory")
    document_name: Optional[str] = Field(None, alias="documentName")
    proceeding_type_category: Optional[str] = Field(None, alias="proceedingTypeCategory")
    subproceeding_type_category: Optional[str] = Field(None, alias="subproceedingTypeCategory")
    document_identifier: Optional[str] = Field(None, alias="documentIdentifier")
    object_uu_id: Optional[str] = Field(None, alias="objectUuId")
    ocr_search_text: Optional[str] = Field(None, alias="ocrSearchText")
    issue_type: Optional[List[str]] = Field(None, alias="issueType")
    board_rulings: Optional[List[str]] = Field(None, alias="boardRulings")
    decision_date: Optional[str] = Field(None, alias="decisionDate")
    identifier: Optional[str] = None
