# ********************************************************************************
# *         WARNING: This file is automatically generated by unasync.py.         *
# *                             DO NOT MANUALLY EDIT                             *
# *           Source File: patent_client/_async/uspto/peds/__init__.py           *
# ********************************************************************************

from .model import Document, USApplication

__api_name__ = "US Patent Examination Data Set"
__all__ = ["USApplication", "Document"]
