# ********************************************************************************
# *         WARNING: This file is automatically generated by unasync.py.         *
# *                             DO NOT MANUALLY EDIT                             *
# *           Source File: patent_client/_async/epo/ops/legal/util.py            *
# ********************************************************************************

"""
Legal Status Codes are located here:
https://www.epo.org/searching-for-patents/data/coverage/weekly.html
"""
